In [1]:
import pandas as pd
import numpy as np

read data

In [119]:
df = pd.read_csv('car/car.data',names= ['buying','maint', 'doors', 'persons', 'lug_boot', 'safety','classes'])
df

     buying  maint  doors persons lug_boot safety classes
0     vhigh  vhigh      2       2    small    low   unacc
1     vhigh  vhigh      2       2    small    med   unacc
2     vhigh  vhigh      2       2    small   high   unacc
3     vhigh  vhigh      2       2      med    low   unacc
4     vhigh  vhigh      2       2      med    med   unacc
...     ...    ...    ...     ...      ...    ...     ...
1723    low    low  5more    more      med    med    good
1724    low    low  5more    more      med   high   vgood
1725    low    low  5more    more      big    low   unacc
1726    low    low  5more    more      big    med    good
1727    low    low  5more    more      big   high   vgood

[1728 rows x 7 columns]

Value mapping

In [122]:
mapping ={'vhigh':4,'high':3,'med':2,'low':1,
        '5more':6,'more':5,
        'small' :1, 'med':2, 'big':3,
        'unacc':1, 'acc':2,'good':3, 'vgood':4
        }
df_map = df.replace(mapping)
df_map

      buying  maint doors persons  lug_boot  safety  classes
0          4      4     2       2         1       1        1
1          4      4     2       2         1       2        1
2          4      4     2       2         1       3        1
3          4      4     2       2         2       1        1
4          4      4     2       2         2       2        1
...      ...    ...   ...     ...       ...     ...      ...
1723       1      1     6       5         2       2        3
1724       1      1     6       5         2       3        4
1725       1      1     6       5         3       1        1
1726       1      1     6       5         3       2        3
1727       1      1     6       5         3       3        4

[1728 rows x 7 columns]

Model training

In [148]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.metrics  import f1_score,accuracy_score,classification_report

#  convert from pandas to numpy
car = df_map.values

# prepare dataset
X,y = car[:,1:], car[:,1]
X,y = X.astype(int), y.astype(int)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=2)

model = RandomForestClassifier(max_depth=None,
                              max_features='auto',
                              n_estimators=500,
                              random_state=0)
model.fit(X_train,y_train)

# We use the predict() on the model to predict the output
pred=model.predict(X_test)

print(accuracy_score(y_test,pred))
target_names = ['vhigh','high','med','low']
print(classification_report(y_test, pred, target_names=target_names))

1.0
              precision    recall  f1-score   support

       vhigh       1.00      1.00      1.00       130
        high       1.00      1.00      1.00       130
         med       1.00      1.00      1.00       118
         low       1.00      1.00      1.00       141

    accuracy                           1.00       519
   macro avg       1.00      1.00      1.00       519
weighted avg       1.00      1.00      1.00       519

In [149]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.metrics  import f1_score,accuracy_score,classification_report

#  convert from pandas to numpy
car = df.values

# prepare dataset
X,y = car[:,1:], car[:,1]
X,y = X.astype(int), y.astype(int)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=2)

dt = DecisionTreeClassifier()
dt.fit(X_train,y_train)

# We use the predict() on the model to predict the output
pred=dt.predict(X_test)

print(accuracy_score(y_test,pred))
target_names = ['vhigh','high','med','low']
print(classification_report(y_test, pred, target_names=target_names))

1.0
              precision    recall  f1-score   support

       vhigh       1.00      1.00      1.00       130
        high       1.00      1.00      1.00       130
         med       1.00      1.00      1.00       118
         low       1.00      1.00      1.00       141

    accuracy                           1.00       519
   macro avg       1.00      1.00      1.00       519
weighted avg       1.00      1.00      1.00       519

In [160]:
test = np.array([[3,4,2,3,3,3],
                [3,4,4,3,3,3],
                [3,4,5,3,3,3]])
dt.predict(test)

array([3, 3, 3])

In [161]:
model.predict(test)

array([3, 3, 3])